[platformio]
default_envs = xiao_esp32c3

[env:xiao_esp32c3]
platform = platformio/espressif32 @ 7.1.3
board = seeed_xiao_esp32c3
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
test_ignore = native/*

[env:native]
platform = native
build_flags = -std=c++17 -Wall -Wextra -Werror
test_filter = native/*
